### ISSUE TITLE
footnote[whatIsPassPhrase] のパスフレーズとパスワードの差

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startSSL#19]
OpenSSHでのパスフレーズは以下の特徴がある。スペースの有無は特に関係ありません。(一般論としてのパスフレーズでどうかはさておき)
  * 長い文字列(1023文字まで)を設定できる <https://github.com/openssh/openssh-portable/blob/14ccfdb7248e33b1dc8bbac1425ace4598e094cb/readpass.c#L125>
  * 認証に直接使うのではなく私有鍵(秘密鍵)の保護に使う

なおOpenSSLやLibreSSLでも1023文字までで同一の制限です。
<https://github.com/libressl-portable/openbsd/blob/5fa2f8777d26cc155a94d87a28b9427eebb2d299/src/usr.bin/openssl/apps.h#L274>

**Comment by mochikoAsTech** [comment]
`//footnote[whatIsPassPhrase][このパスフレーズは秘密鍵の保護に用いられます。パスフレーズを設定しなくてよいのか、についてはコラムで後述します]`
とします。
