### ISSUE TITLE
メリットの[表示速度が上がる]について

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startSSL#20]
HTTPS化すると得られるメリット[5.5.1 表示速度が上がる]に関して、速度が上がる保証はないです。
EDHで重たいパラメータの鍵共有をしてたらまずアウトですし、HTTP/2 が速いかどうかは状況によります。
関連: https://twitter.com/takehora/status/1203611997255819266

多くのブラウザでHTTP/2を使いたかったら HTTP/2 over TLSにせざるをえないので、「HTTP/2 が使えるようになる」だったらメリットといえるかもしれません。強調すべきところかどうかはさておき。

**Comment by mochikoAsTech** [comment]
HTTPS化するとHTTP/2が使えるようになる、使うとサイトの作りによっては速くなるケースもある、という表現に改めました。
ありがとうございます！
