### ISSUE TITLE
SSH初回接続時の確認 [WindowsのRLoginを使ってサーバに入ってみよう]

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startSSL#21]
【このホストの公開鍵を信頼して接続しますか？】はホストを信頼するのではなくて、「この公開鍵は本物のサーバですか?」「MITM攻撃されて偽者に繋がっていませんね?」ということを確認しろといっているだけです。

SSHでは相手のホスト鍵が本物(経路上でMITM攻撃されていない)かどうかは、別の経路でfingerprintを確認しなければ(本来は)いけません(ホスト認証で証明書を使っている場合は例外)。
たとえば githubでは https://help.github.com/en/github/authenticating-to-github/githubs-ssh-key-fingerprints のように確認手段を提供しています。
Oracle Cloud でできるかは知りませんが、https接続した(信頼できる接続の)コンソールから `ssh-keygen -l -f /etc/ssh/ssh_host_ecdsa_key.pub` のようにして確認したものと比較するのが本来の運用です。(もし管理者が別人なら管理者に安全な経路で教えてもらう必要がある)

大抵の人は初回からMITM攻撃されるわけねーだろ(あるいはそもそも知らずに)、でエイヤとyesを叩きます。が、暗号周りの本であれば注意書きは要ります。

  * 確認せずyesと叩くのは悪い見本であり、本来はホスト鍵の確認が必要である
  * 初回からずっとMITM攻撃を受けるリスクを無視できるものとして手間を省いている

あたりが思いつく注意書きの趣旨でしょうか。

なお2回目接続以降の【これは前に信頼していいって言われたサーバだ!】も不正確です。
「これは前に信頼したホスト鍵と一致した!」が意味としては正しいです。
(yesとしてホスト鍵を受け入れたときと比較して)経路上でホスト鍵をスリ替える攻撃を受けていないということです。

**Comment by mochikoAsTech** [comment]
ありがとうございます。
より正確になるよう修正して、注釈を足しました。
