### ISSUE TITLE
パスフレーズを二要素認証として説明しなくてもよい  [【コラム】SSHの秘密鍵にパスフレーズは設定すべき？]

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startSSL#22]
SSH私有鍵(秘密鍵)に設定するパスフレーズを二要素認証として説明すると、「手元の鍵のパスフレーズを変更した場合に、サーバ側でも何か設定しなければいけないのではないか」という無駄な不安を生みそうです。
(そもそも二要素認証の定義に合致するかどうかはさておきます)

サーバ側としては1要素しか見ていませんし、私有鍵(秘密鍵)の保護に関してはスマホの喩えのみで充分かと思います。

ただ、ロック画面解除に使うものを「パスワード」とするとパスワード認証との字面の一致があって不親切です。PINとか暗証番号とか「パス」を含まずスマホのロックに使う別の表現を持ち出すと無難かと思います(スマホ用語的には不正確になりえますが)。

**Comment by mochikoAsTech** [comment]
- `スマホ本体が盗まれてしまっても、暗証番号が分からなければロック画面が解除できず、勝手に使えないのと同じです。`にしました。
- `なお手元の秘密鍵に後からパスフレーズを設定しても、サーバ側での変更は特に必要ありません。`の説明を追加しました。
