### ISSUE TITLE
Macでのssh-keygen後のchmod 600は不要

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startSSL#23]
[Mac で SSH のキーペア(秘密鍵・公開鍵)を作成する]の部分について

ssh-keygenはうまいことパーミッションを設定してくれるはずなので(要Mac環境で実験)、chmod 600は不要のはずです。どうしても要る場合でも umask 077; umask 022 で挟めば足ります。
また `ssh-keygen -N '' -f ~/Desktop/startSSLKey` で空のパスフレーズ (-N '')を指示しておけば説明の手間の節約になります。

**Comment by mochikoAsTech** [comment]
`ssh-keygen -N '' -f ~/Desktop/startSSLKey`
知らなかった！いいこと聞いた！ありがとうございます！

> ssh-keygenはうまいことパーミッションを設定してくれるはず

私もそう思ってたんですが、実際にハンズオンをした際に
複数名のMacユーザがここでひっかかって、`chmod 600`で解消する事案があったので入れています。
umask変えてumask戻すでもいいのは分かりますが、Macで再検証になるので一旦chmodのままとします。
