### ISSUE TITLE
startssl.key のパーミッション指定

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startSSL#24]
* 秘密鍵（startssl.key）を作ろう
  * 【コラム】SSL証明書の秘密鍵にパスフレーズは設定すべき？

に影響します。

SSH私有鍵(秘密鍵)と異なり、startssl.key のパーミッションについて操作している記述が見当たりません。
ページ数とパーミッションを開けている時間のためには
```
# umask 077
# openssl genrsa 2048 >/etc/nginx/ssl/startssl.key
# umask 022
```
のように umask 077 してから生成すると手っ取り早いです。
丁寧に書くと https://www.fujissl.jp/docs/d001/ みたいになります。

umask復元の説明を省くなら直後にchmodする手もあります。
```
# openssl genrsa 2048 >/etc/nginx/ssl/startssl.key
# chmod 600 /etc/nginx/ssl/startssl.key
```

**Comment by mochikoAsTech** [comment]
完全に抜けてました。ありがとうございます！
直後にchmodする手順を追記しておきます。
（作ってからchmodで権限変更だと一瞬権限がゆるい時間ができてしまうけど、umaskを変えて作ってumaskを戻しての3ステップにれば、それがないんですね。なるほど。umaskを使う場合は、その説明も入れたいので、一旦SSHの方と同様にchmodでいきます。）

コラムの方は本手順ではなく、パスフレーズありの秘密鍵を作る方法の解説のみなので、chmodは省略します。
