### ISSUE TITLE
一部文章表現について

### ISSUE THREAD

**Issue by hs-yonekura** [mochikoAsTech/startSSL#25]
どれも誤記とは言えない軽微なもので修正は不要かもしれません。
少しだけ個人的に気になった表現だけご連絡いたします！

- P.47:   
   ```
   OCPUが2、メモリが16GBの...
   ```
   という箇所ですが、ORACLE CloudのUIに合わせるとすると下記の方が良いかもしれません。基本的にカタカナ語は音引き無しで統一されているので修正が必要かは微妙なところですが :sweat_smile:
   ```
   OCPUが2、メモリー(GB)が16の...
   ```

- p.57:
`▲図 3.4`と `[KeepAlive...`の縦位置ズレ

- p.72:
`vi（ブイアイ）`ですが、もしかしたら`vi（ヴィーアイ）`の方がベターかもしれません。
Wikiや出典は不明ですが下記サイトでは、ヴィーアイが正式名称と言っているようです。
https://wp-p.info/tpl_rep.php?cat=unix_linux-biginner&fl=r19

- p.88:
`SSL証明書＋中間CA証明書...`のインデントは他と同様一つ浅くした方が良いようです。

- p.102:
`コピーペースト`は、p.41と同様`コピー&ペースト`に合わせた方がベターかもしれません。

- p.105:
末尾の`READMEはファイルの説明書です。`は拡張子も含めて`README.txtはファイルの説明書です。`の方がベターと思いました。

- p.4/53/106/118/122/123/124/131/135/136
「な抜き」と「な有り」の表記揺れが少しあります。「な抜き」に統一する方がベターと思いました。

- p.136:
`どなた宛てですか？・・・誰と`の？と三点リーダーの間に全角スペースを入れても良いと思いました。
`どなた宛てですか？　・・・誰と`

**Comment by mochikoAsTech** [comment]
ありがとうございます！

> 「な抜き」と「な有り」の表記揺れが少しあります。「な抜き」に統一する方がベターと思いました。

校正してページ番号が動いた結果、どれだか分からなくなっちゃったので、
もう少し詳しく…教えてください…！

**Comment by mochikoAsTech** [comment]
取りあえず反映したのでクローズ。
「な抜き」については別Issueで聞く。
