### ISSUE TITLE
ssl_ciphers が長すぎてハミ出る [NGINX で HTTPS のバーチャルホストを作ろう]

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startSSL#27]
ssl_ciphers の行が長すぎて紙面からハミ出ています。

現状:
```
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256;
```

NGINX的に改行を入れられるスタイルがあるならそれで、あるいは `ssl_ciphers ECDHE+AESGCM:DHE+AESGCM:!DSS:!EXP:!LOW` とでもすると同値で短くなるはずです。
実機で `openssl ciphers -V` の確認は必要ですが。

**Comment by mochikoAsTech** [comment]
おお、はみでてた！
ありがとうございます。修正します。
