### ISSUE TITLE
scp不要なSSH私有鍵がコピー対象に含まれている [Mac で証明書と中間 CA 証明書をアップしよう]

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startSSL#29]
サーバに置く必要の無いSSH私有鍵 `~/Desktop/startSSLKey` がコピー対象に含まれています。

現状: `scp -i ~/Desktop/startSSLKey server.crt ca-bundle.ca opc@パブリックIPアドレス:/home/opc/`
修正: `scp -i server.crt ca-bundle.ca opc@パブリックIPアドレス:/home/opc/`

**Comment by mochikoAsTech** [comment]
[-i identityファイル]の指定なので、コピー対象にはなっていないです。

**Comment by kaoru6** [comment]
失礼しました。完全に-i見落としていました。
