### ISSUE TITLE
今といまの表記揺れ

### ISSUE THREAD

**Issue by assarisari57** [mochikoAsTech/startSSL#3]
「今・いま」という文字の前後の文字がひらがなか漢字かなどによって、いまと今を使い分けるべきなのだと思うのですがどういう基準で書いているのか判断できずだったので、確認いただきたいです。

いま
**いま**理由を説明するので落ち着いてください
あなたが**いま** Oracle Cloud で立てようとしたサーバは
「ごめんね、無料マンションは大人気で **いま**空き部屋がないの」
**いま**選択されている[VM.Standard.E2.1.Micro]から
**いま**立てた「VM.Standard.E2.2」を 1 ヶ月使
皆さんが**いま**使って

今
認証キーリスト]に、**今**作った[startSSLKey]が表示されたら、キー
**今**すぐに下記のリンクからログインして

**Comment by mochikoAsTech** [comment]
ありがとうございます。

基本的には「いま」を使用します。
ただし、画面に表示されている `［今すぐ始める（無償）］` などの表記は、実際に表示されている文言をそのまま使用します。

既存の原稿の修正はこちらで行ないます！
