### ISSUE TITLE
CAAレコード

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startSSL#30]
CAAレコードについて記述が見当たりません。意図してまるまる記述を外しているのであればよいのですが、そうでないなら以下のいずれかで対応できるかと思います。

 * DNS本5.5へのポインタを示す
 * DNS本5.5のコピーを置く

**Comment by mochikoAsTech** [comment]
重複するものは書かない方針ですが、footnoteで参照先は追記しました。
